FROM golang:alpine
RUN mkdir /app
ADD . /app/
WORKDIR /app
COPY go.mod .
COPY go.sum .
COPY .env .
RUN go mod download
RUN go build -o main .
RUN adduser -S -D -H -h /app kittycat
USER kittycat
CMD ["./main"]